# Generated by Django 4.0.2 on 2022-02-20 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userrecharge',
            name='operator_id',
            field=models.BigIntegerField(),
        ),
        migrations.AlterField(
            model_name='userrecharge',
            name='phone_number',
            field=models.BigIntegerField(),
        ),
    ]
